-- Arbiter account-level Snowflake setup.
-- Run as ACCOUNTADMIN.
-- All CREATE statements are idempotent and safe to run again.

USE ROLE ACCOUNTADMIN;

-- 1. Existing warehouse is expected to be COMPUTE_WH. This creates it only
-- if it does not exist.
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Arbiter supply-chain analytics warehouse';

-- 2. Main analytics database.
CREATE DATABASE IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY;

-- 3. Source, staging, canonical, governance, semantic, agent, and audit schemas.
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.RAW_INVENTORY;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.RAW_PROCUREMENT;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.RAW_OLIST;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.RAW_DATACO;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.RAW_SHIPMENT_PRICING;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.RAW_NIST;

CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.STG_INVENTORY;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.STG_PROCUREMENT;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.STG_OLIST;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.STG_DATACO;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.STG_SHIPMENT_PRICING;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.STG_NIST;

CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.CORE;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.GOVERNANCE;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.SEMANTIC;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.AGENT;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.AUDIT;

-- 4. Least-privilege runtime roles.
CREATE ROLE IF NOT EXISTS ROLE_AGENT_READ;
CREATE ROLE IF NOT EXISTS ROLE_APPLICATION;
CREATE ROLE IF NOT EXISTS ROLE_AUDITOR;

-- 5. Runtime role access.
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_APPLICATION;
GRANT USAGE ON DATABASE SUPPLY_CHAIN_ONTOLOGY TO ROLE ROLE_AGENT_READ;
GRANT USAGE ON DATABASE SUPPLY_CHAIN_ONTOLOGY TO ROLE ROLE_APPLICATION;

GRANT USAGE ON SCHEMA SUPPLY_CHAIN_ONTOLOGY.GOVERNANCE TO ROLE ROLE_AGENT_READ;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_ONTOLOGY.SEMANTIC TO ROLE ROLE_AGENT_READ;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_ONTOLOGY.AGENT TO ROLE ROLE_AGENT_READ;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_ONTOLOGY.AUDIT TO ROLE ROLE_APPLICATION;

GRANT ROLE ROLE_AGENT_READ TO ROLE ROLE_APPLICATION;

-- 6. Assign the runtime role to the current user.
GRANT ROLE ROLE_APPLICATION TO USER DEVANSHVASHIST;

-- 7. Optional defaults for the development user.
ALTER USER DEVANSHVASHIST SET DEFAULT_ROLE = ROLE_APPLICATION;
ALTER USER DEVANSHVASHIST SET DEFAULT_WAREHOUSE = COMPUTE_WH;

-- 8. Verification.
SHOW WAREHOUSES LIKE 'COMPUTE_WH';
SHOW DATABASES LIKE 'SUPPLY_CHAIN_ONTOLOGY';
SHOW SCHEMAS IN DATABASE SUPPLY_CHAIN_ONTOLOGY;
SHOW ROLES LIKE 'ROLE_APPLICATION';
SHOW GRANTS TO USER DEVANSHVASHIST;
