-- Arbiter Snowflake foundation.
-- Run with a deployment role, then grant the app role only semantic access.

CREATE DATABASE IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY;

CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.RAW_INVENTORY;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.RAW_PROCUREMENT;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.RAW_OLIST;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.RAW_DATACO;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.RAW_SHIPMENT_PRICING;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.RAW_NIST;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.STG_INVENTORY;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.STG_PROCUREMENT;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.STG_OLIST;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.STG_DATACO;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.STG_SHIPMENT_PRICING;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.STG_NIST;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.GOVERNANCE;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.CORE;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.SEMANTIC;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.AGENT;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.AUDIT;

CREATE TABLE IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.GOVERNANCE.METRIC_REGISTRY (
    metric_id VARCHAR NOT NULL,
    metric_name VARCHAR NOT NULL,
    definition VARCHAR NOT NULL,
    grain VARCHAR NOT NULL,
    semantic_view VARCHAR NOT NULL,
    date_policy VARCHAR NOT NULL,
    currency_policy VARCHAR,
    status VARCHAR NOT NULL DEFAULT 'ACTIVE',
    version NUMBER NOT NULL DEFAULT 1,
    steward VARCHAR NOT NULL,
    created_at TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (metric_id, version)
);

CREATE TABLE IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.GOVERNANCE.ENTITY_IDENTIFIER_MAP (
    canonical_entity_type VARCHAR NOT NULL,
    canonical_entity_id VARCHAR NOT NULL,
    source_system VARCHAR NOT NULL,
    source_identifier VARCHAR NOT NULL,
    match_method VARCHAR NOT NULL,
    match_confidence NUMBER(5,4) NOT NULL,
    approval_status VARCHAR NOT NULL DEFAULT 'PENDING',
    approved_by VARCHAR,
    UNIQUE (canonical_entity_type, source_system, source_identifier)
);

CREATE TABLE IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.GOVERNANCE.JOIN_PATH_REGISTRY (
    join_path_id VARCHAR PRIMARY KEY,
    source_view VARCHAR NOT NULL,
    target_view VARCHAR NOT NULL,
    path_definition VARCHAR NOT NULL,
    fanout_policy VARCHAR NOT NULL,
    status VARCHAR NOT NULL DEFAULT 'ACTIVE',
    version NUMBER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.AGENT.QUERY_PLAN (
    query_plan_id VARCHAR PRIMARY KEY,
    trace_id VARCHAR NOT NULL,
    metric_id VARCHAR NOT NULL,
    semantic_view VARCHAR NOT NULL,
    approved_join_path_id VARCHAR,
    plan_json VARIANT NOT NULL,
    decision_status VARCHAR NOT NULL,
    created_at TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS SUPPLY_CHAIN_ONTOLOGY.AUDIT.AGENT_RUN (
    trace_id VARCHAR PRIMARY KEY,
    question VARCHAR NOT NULL,
    persona VARCHAR,
    decision_status VARCHAR NOT NULL,
    ontology_version VARCHAR,
    metric_registry_version VARCHAR,
    semantic_view_version VARCHAR,
    created_at TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
