-- Least-privilege application roles.
-- Execute grants according to the account's security policy.

CREATE ROLE IF NOT EXISTS ROLE_AGENT_READ;
CREATE ROLE IF NOT EXISTS ROLE_APPLICATION;
CREATE ROLE IF NOT EXISTS ROLE_AUDITOR;

GRANT USAGE ON DATABASE SUPPLY_CHAIN_ONTOLOGY TO ROLE ROLE_AGENT_READ;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_ONTOLOGY.SEMANTIC TO ROLE ROLE_AGENT_READ;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_ONTOLOGY.GOVERNANCE TO ROLE ROLE_AGENT_READ;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_ONTOLOGY.AGENT TO ROLE ROLE_AGENT_READ;
GRANT SELECT ON ALL VIEWS IN SCHEMA SUPPLY_CHAIN_ONTOLOGY.SEMANTIC TO ROLE ROLE_AGENT_READ;
GRANT SELECT ON ALL TABLES IN SCHEMA SUPPLY_CHAIN_ONTOLOGY.GOVERNANCE TO ROLE ROLE_AGENT_READ;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA SUPPLY_CHAIN_ONTOLOGY.AGENT TO ROLE ROLE_AGENT_READ;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SUPPLY_CHAIN_ONTOLOGY.SEMANTIC TO ROLE ROLE_AGENT_READ;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SUPPLY_CHAIN_ONTOLOGY.GOVERNANCE TO ROLE ROLE_AGENT_READ;

GRANT ROLE ROLE_AGENT_READ TO ROLE ROLE_APPLICATION;
GRANT USAGE ON DATABASE SUPPLY_CHAIN_ONTOLOGY TO ROLE ROLE_APPLICATION;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_ONTOLOGY.AUDIT TO ROLE ROLE_APPLICATION;
GRANT INSERT ON ALL TABLES IN SCHEMA SUPPLY_CHAIN_ONTOLOGY.AUDIT TO ROLE ROLE_APPLICATION;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_ONTOLOGY.AUDIT TO ROLE ROLE_AUDITOR;
GRANT SELECT ON ALL TABLES IN SCHEMA SUPPLY_CHAIN_ONTOLOGY.AUDIT TO ROLE ROLE_AUDITOR;
